// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhuongXa.Infrastructure.DuLieu;

#nullable disable

namespace PhuongXa.Infrastructure.DuLieu.Migrations
{
    [DbContext(typeof(BuiCanhCSDL))]
    [Migration("20260406184431_AddPaymentAndDepartment")]
    partial class AddPaymentAndDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.AlbumPhuongTien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnhBia")
                        .HasColumnType("text");

                    b.Property<string>("ChuDe")
                        .HasColumnType("text");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlbumPhuongTiens");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.BaiViet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DanhMucId")
                        .HasColumnType("uuid");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTaMeta")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXuatBan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("boolean");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SoLuotXem")
                        .HasColumnType("integer");

                    b.Property<Guid>("TacGiaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TheTag")
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDeMeta")
                        .HasColumnType("text");

                    b.Property<string>("TomTat")
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DaXoa");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.HasIndex("NgayXuatBan");

                    b.HasIndex("TacGiaId");

                    b.HasIndex("TrangThai");

                    b.HasIndex("DanhMucId", "TrangThai", "NgayXuatBan");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.BinhLuan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaiVietId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailKhach")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenKhach")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaiVietId");

                    b.HasIndex("ChaId");

                    b.HasIndex("DaDuyet");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("BaiVietId", "DaDuyet");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.CaiDatTrangWeb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Loai")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Khoa")
                        .IsUnique();

                    b.ToTable("CaiDatTrangWebs");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.DanhMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("boolean");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Loai")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChaId");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.DichVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanCuPhapLy")
                        .HasColumnType("text");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DanhMucId")
                        .HasColumnType("uuid");

                    b.Property<string>("GiayToCanThiet")
                        .HasColumnType("text");

                    b.Property<decimal?>("LePhi")
                        .HasColumnType("numeric");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuyTrinh")
                        .HasColumnType("text");

                    b.Property<int>("SoNgayXuLy")
                        .HasColumnType("integer");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("integer");

                    b.Property<string>("UrlBieuMau")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.HasIndex("MaDichVu")
                        .IsUnique();

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.DonUngDichVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("DiaChiNguoiNop")
                        .HasColumnType("text");

                    b.Property<Guid>("DichVuId")
                        .HasColumnType("uuid");

                    b.Property<string>("DienThoaiNguoiNop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DuongDanBienLai")
                        .HasColumnType("text");

                    b.Property<string>("EmailNguoiNop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("GhiChuNguoiXuLy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HanXuLy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HeThongThanhToan")
                        .HasColumnType("text");

                    b.Property<decimal?>("LePhiDaNop")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LePhiTaiThoiDiemNop")
                        .HasColumnType("numeric");

                    b.Property<string>("MaThamChieuThanhToan")
                        .HasColumnType("text");

                    b.Property<string>("MaTheoDoi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayHenTra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NgayThanhToan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NguoiXuLyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhongBanHienTaiId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenNguoiNop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThamChieuGiaoDich")
                        .HasColumnType("text");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiThanhToanLePhi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DichVuId");

                    b.HasIndex("MaTheoDoi")
                        .IsUnique();

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("NguoiXuLyId");

                    b.HasIndex("PhongBanHienTaiId");

                    b.HasIndex("TrangThai");

                    b.ToTable("DonUngDichVus");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.LichSuTrangThaiDonUng", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DonUngId")
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NguoiThayDoiId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrangThaiCu")
                        .HasColumnType("integer");

                    b.Property<int>("TrangThaiMoi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonUngId");

                    b.HasIndex("NguoiThayDoiId");

                    b.ToTable("LichSuTrangThaiDonUngs");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.MaLamMoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaBiThuHoi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("HetHanLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<string>("TaoBoiIp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaToken")
                        .IsUnique();

                    b.HasIndex("NguoiDungId");

                    b.ToTable("MaLamMois");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.NhatKyKiemTra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DiaChiIp")
                        .HasColumnType("text");

                    b.Property<string>("GiaTriCu")
                        .HasColumnType("text");

                    b.Property<string>("GiaTriMoi")
                        .HasColumnType("text");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<string>("TacNhanNguoiDung")
                        .HasColumnType("text");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("text");

                    b.Property<string>("TenThucThe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ThucTheId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TenThucThe");

                    b.HasIndex("ThoiGian");

                    b.ToTable("NhatKyKiemTras");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.PhongBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("boolean");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.PhuongTien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("DuongDanTep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("KichThuocTep")
                        .HasColumnType("bigint");

                    b.Property<int>("Loai")
                        .HasColumnType("integer");

                    b.Property<string>("LoaiNoiDung")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NguoiTaiLenId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenTep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlTep")
                        .HasColumnType("text");

                    b.Property<string>("VanBanThayThe")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("NguoiTaiLenId");

                    b.ToTable("PhuongTiens");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.TepDonUng", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DonUngId")
                        .HasColumnType("uuid");

                    b.Property<string>("DuongDanTep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("KichThuocTep")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiNoiDung")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenTep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlTep")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonUngId");

                    b.ToTable("TepDonUngs");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.ThongBao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("LienKet")
                        .HasColumnType("text");

                    b.Property<int>("Loai")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NguoiDungId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId", "DaDoc");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.TinNhanLienHe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("DienThoai")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TinNhanLienHes");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.VaiTro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.BaiViet", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.DanhMuc", "DanhMuc")
                        .WithMany("DanhSachBaiViet")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", "TacGia")
                        .WithMany("DanhSachBaiViet")
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.BinhLuan", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.BaiViet", "BaiViet")
                        .WithMany("DanhSachBinhLuan")
                        .HasForeignKey("BaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhuongXa.Domain.CacThucThe.BinhLuan", "Cha")
                        .WithMany("DanhSachTraLoi")
                        .HasForeignKey("ChaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachBinhLuan")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BaiViet");

                    b.Navigation("Cha");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.DanhMuc", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.DanhMuc", "Cha")
                        .WithMany("DanhSachCon")
                        .HasForeignKey("ChaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cha");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.DichVu", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.DanhMuc", "DanhMuc")
                        .WithMany("DanhSachDichVu")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.DonUngDichVu", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.DichVu", "DichVu")
                        .WithMany("DanhSachDonUng")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachDonUng")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", "NguoiXuLy")
                        .WithMany()
                        .HasForeignKey("NguoiXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhuongXa.Domain.CacThucThe.PhongBan", "PhongBanHienTai")
                        .WithMany()
                        .HasForeignKey("PhongBanHienTaiId");

                    b.Navigation("DichVu");

                    b.Navigation("NguoiDung");

                    b.Navigation("NguoiXuLy");

                    b.Navigation("PhongBanHienTai");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.LichSuTrangThaiDonUng", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.DonUngDichVu", "DonUng")
                        .WithMany("LichSuTrangThai")
                        .HasForeignKey("DonUngId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", "NguoiThayDoi")
                        .WithMany()
                        .HasForeignKey("NguoiThayDoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonUng");

                    b.Navigation("NguoiThayDoi");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.MaLamMoi", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.NhatKyKiemTra", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachNhatKy")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.PhuongTien", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.AlbumPhuongTien", "Album")
                        .WithMany("DanhSachPhuongTien")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", "NguoiTaiLen")
                        .WithMany("DanhSachTaiLen")
                        .HasForeignKey("NguoiTaiLenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("NguoiTaiLen");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.TepDonUng", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.DonUngDichVu", "DonUng")
                        .WithMany("DanhSachTep")
                        .HasForeignKey("DonUngId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonUng");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.ThongBao", b =>
                {
                    b.HasOne("PhuongXa.Domain.CacThucThe.NguoiDung", "NguoiDung")
                        .WithMany("DanhSachThongBao")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.AlbumPhuongTien", b =>
                {
                    b.Navigation("DanhSachPhuongTien");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.BaiViet", b =>
                {
                    b.Navigation("DanhSachBinhLuan");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.BinhLuan", b =>
                {
                    b.Navigation("DanhSachTraLoi");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.DanhMuc", b =>
                {
                    b.Navigation("DanhSachBaiViet");

                    b.Navigation("DanhSachCon");

                    b.Navigation("DanhSachDichVu");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.DichVu", b =>
                {
                    b.Navigation("DanhSachDonUng");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.DonUngDichVu", b =>
                {
                    b.Navigation("DanhSachTep");

                    b.Navigation("LichSuTrangThai");
                });

            modelBuilder.Entity("PhuongXa.Domain.CacThucThe.NguoiDung", b =>
                {
                    b.Navigation("DanhSachBaiViet");

                    b.Navigation("DanhSachBinhLuan");

                    b.Navigation("DanhSachDonUng");

                    b.Navigation("DanhSachNhatKy");

                    b.Navigation("DanhSachTaiLen");

                    b.Navigation("DanhSachThongBao");
                });
#pragma warning restore 612, 618
        }
    }
}
